# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170731_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Collection', verbose_name='Коллекция'),
        ),
    ]
