# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='collection',
        ),
    ]
