# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='скидка в %'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='цена со скидкой в ₸'),
        ),
    ]
