# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20171005_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
