# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='banner/photos', verbose_name='изображение')),
                ('url', models.URLField(default=None, null=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
